# AUTO-GENERATED by tools/strategy_manifest — DO NOT EDIT
# Regenerate: python -m tools.strategy_manifest generate

GENERATED_LEGACY_META_KEYS: dict = {
    'BankNiftyBTST': 'banknifty_btst',
    'LiquiditySweepStrategy': 'liquidity_sweep',
    'NiftyIntradayMagicalLine': 'nifty_intraday_magical_line',
    'OIPositionalBuy': 'oi_positional_buy',
    'OneDayMagicalLine': 'one_day_magical_line',
    'RSIBreadAndButter': 'rsi_bread_butter',
}

GENERATED_META_ALIASES: dict = {
    'one_day_ml1': 'one_day_magical_line',
}
