# AUTO-GENERATED by tools/strategy_manifest — DO NOT EDIT
# Regenerate: python -m tools.strategy_manifest generate

STRATEGY_PROFILES: dict = {
    'BankNiftyBTST': {
        'symbols': [
            'BANKNIFTY',
        ],
        'exchange': 'NSE',
        'eval_mode': 'scheduled',
        'live': {
            'exchange': 'INDEX',
            'sector': 'YES',
        },
        'backtest': {
            'start_date': '2026-01-02',
            'end_date': '2026-02-19',
            'timeframe': '5',
            'exchange': 'INDEX',
            'sector': 'YES',
        },
    },
    'FuturesEMAHighLow': {
        'symbols': [
            'NIFTY',
        ],
        'exchange': 'NSE',
        'live': {
            'exchange': 'INDEX',
            'sector': 'YES',
        },
        'backtest': {
            'start_date': '2024-02-01',
            'end_date': '2026-03-02',
            'timeframe': '60',
            'exchange': 'INDEX',
            'sector': 'YES',
        },
    },
    'Futures_EMA_Momentum': {
        'symbols': [
            'BTCUSD',
        ],
        'exchange': 'NSE',
        'delta': {
            'india': True,
            'testnet': False,
            'leverage': 1,
        },
        'live': {
            'exchange': 'INDEX',
            'sector': 'YES',
        },
        'backtest': {
            'start_date': '2024-09-01',
            'end_date': '2026-03-13',
            'timeframe': '60',
            'exchange': 'INDEX',
            'sector': 'YES',
        },
    },
    'IPOBreakout': {
        'exchange': 'NSE',
        'live': {
            'exchange': 'NSE',
            'sector': 'NO',
            'ipo_days': 365,
            'ipo_filter': {
                'price_above': 200,
                'volume_above': 500000,
            },
            'ipo_max_symbols': 50,
        },
        'backtest': {
            'start_date': '2022-01-01',
            'end_date': '2026-02-20',
            'timeframe': 'DAY',
            'exchange': 'NSE',
            'sector': 'NO',
            'ipo_days': 365,
            'ipo_filter': {
                'price_above': 200,
                'volume_above': 500000,
            },
            'ipo_max_symbols': 50,
            'ipo_fallback_symbols': [
                'RELIANCE',
            ],
        },
    },
    'LEAPS_RSI': {
        'symbols': [
            'NIFTY',
        ],
        'exchange': 'NSE',
        'live': {
            'exchange': 'INDEX',
            'sector': 'YES',
            'rsi': 'YES',
        },
        'backtest': {
            'start_date': '2026-01-01',
            'end_date': '2026-05-24',
            'timeframe': '60',
            'exchange': 'INDEX',
            'sector': 'YES',
        },
    },
    'LiquiditySweepStrategy': {
        'symbols': [
            'BTCUSD',
            'ETHUSD',
        ],
        'exchange': 'NSE',
        'delta': {
            'india': True,
            'testnet': False,
            'leverage': 5,
        },
        'live': {
            'exchange': 'DELTA',
            'sector': 'YES',
        },
        'backtest': {
            'start_date': '2026-06-02',
            'end_date': '2026-07-03',
            'timeframe': '1',
            'exchange': 'DELTA',
            'sector': 'YES',
        },
    },
    'MagicalLines': {
        'symbols': [
            'NIFTY',
        ],
        'exchange': 'NSE',
        'live': {
            'exchange': 'INDEX',
            'sector': 'YES',
        },
        'backtest': {
            'start_date': '2026-01-01',
            'end_date': '2026-02-19',
            'timeframe': 'DAY',
            'exchange': 'INDEX',
            'sector': 'YES',
        },
    },
    'NiftyIntradayMagicalLine': {
        'symbols': [
            'NIFTY',
        ],
        'exchange': 'NSE',
        'live': {
            'exchange': 'INDEX',
            'sector': 'YES',
        },
        'backtest': {
            'start_date': '2026-01-02',
            'end_date': '2026-02-19',
            'timeframe': '15',
            'exchange': 'INDEX',
            'sector': 'YES',
        },
    },
    'OIPositionalBuy': {
        'symbols': [
            'NIFTY',
        ],
        'exchange': 'NSE',
        'live': {
            'exchange': 'INDEX',
            'sector': 'YES',
        },
        'backtest': {
            'start_date': '2026-04-01',
            'end_date': '2026-04-28',
            'timeframe': '15',
            'exchange': 'INDEX',
            'sector': 'YES',
        },
    },
    'OneDayMagicalLine': {
        'symbols': [
            'BTCUSD',
        ],
        'exchange': 'NSE',
        'delta': {
            'india': True,
            'testnet': False,
            'leverage': 10,
        },
        'live': {
            'exchange': 'DELTA',
            'sector': 'YES',
        },
        'backtest': {
            'start_date': '2026-02-01',
            'end_date': '2026-02-26',
            'timeframe': '60',
            'exchange': 'DELTA',
            'sector': 'YES',
        },
    },
    'OptionBuildup': {
        'symbols': [
            'NIFTY',
        ],
        'exchange': 'NSE',
        'live': {
            'exchange': 'INDEX',
            'sector': 'YES',
        },
        'backtest': {
            'start_date': '2026-04-01',
            'end_date': '2026-04-28',
            'timeframe': '15',
            'exchange': 'INDEX',
            'sector': 'YES',
        },
    },
    'RSIBreadAndButter': {
        'symbols': [
            'BTCUSD',
        ],
        'exchange': 'NSE',
        'delta': {
            'india': True,
            'testnet': False,
            'leverage': 5,
        },
        'live': {
            'exchange': 'DELTA',
            'sector': 'YES',
        },
        'backtest': {
            'start_date': '2026-07-02',
            'end_date': '2026-07-03',
            'timeframe': '1',
            'exchange': 'DELTA',
            'sector': 'YES',
        },
    },
    'SignalFloodTest': {
        'exchange': 'NSE',
        'live': {
            'exchange': 'INDEX',
            'sector': 'YES',
        },
        'backtest': {
            'start_date': '2024-03-20',
            'end_date': '2024-03-25',
            'timeframe': '1',
            'exchange': 'INDEX',
            'sector': 'YES',
        },
    },
}
