# AUTO-GENERATED by tools/strategy_manifest — DO NOT EDIT
# Regenerate: python -m tools.strategy_manifest generate

from run.config import RunMode

from core.strategies.BTST.BankNiftyBTST.BankNiftyBTST import BankNiftyBTST
from core.strategies.Equity.IPOBreakout.IPOBreakout import IPOBreakout
from core.strategies.Equity.SuperTrendStockRider.SuperTrendStockRider import SuperTrendStockRider
from core.strategies.Futures.Futures_EMA.Futures_EMA import FuturesEMAHighLow
from core.strategies.Futures.Futures_EMA_Momentum.Futures_EMA_Momentum import FuturesEMAMomentum
from core.strategies.IBBM.Leaps.LeapsQuatery_RSI_52_32 import LeapsQuarterly
from core.strategies.IBBM.NiftyDOS.NiftyDOS import NiftyDOS
from core.strategies.IBBM.SMA9Weekly.NiftySMA9Weekly import NiftySMA9Weekly
from core.strategies.MagicalLines.MagicalLines import MagicalLines
from core.strategies.MagicalLines.NiftyIntradayMagicalLine.NiftyIntradayMagicalLine import NiftyIntradayMagicalLine
from core.strategies.OpenIntrest.OIPostionalBuy.OIPosBuy import OIPositionalBuy
from core.strategies.OpenIntrest.optionbuildup.optionbuildup import OptionBuildup
from core.strategies.PipelineTest.signal_flood_test import SignalFloodTestStrategy
from core.strategies.crypto.BTCZeroDteElevenPM.BTCZeroDTEElevenPM import BTCZeroDTEElevenPM
from core.strategies.crypto.BTCZeroDteThreeFifteen.BTCZeroDTE import BTCZeroDTE
from core.strategies.crypto.DirectionalOptionSelling.DirectionalOptionSelling import DirectionalOptionSelling
from core.strategies.crypto.LiquiditySweepStrategy.LiquiditySweepStrategy import LiquiditySweepStrategy
from core.strategies.crypto.RSIBreadAndButter.RSIBreadAndButter import RSIBreadAndButter
from core.strategies.crypto.oneDayMagicalLine.oneDayMagicalLine import OneDayMagicalLine

GENERATED_STRATEGY_MAP = {
        'BTCZeroDTE': {
        "strategy": BTCZeroDTE,
        "instrument": 'OPTION',
        "allowed_modes": [
            RunMode.BACKTEST,
            RunMode.PAPER,
            RunMode.LIVE,
        ],
    },
    'BTCZeroDTEElevenPM': {
        "strategy": BTCZeroDTEElevenPM,
        "instrument": 'OPTION',
        "allowed_modes": [
            RunMode.BACKTEST,
            RunMode.PAPER,
            RunMode.LIVE,
        ],
    },
    'BankNiftyBTST': {
        "strategy": BankNiftyBTST,
        "instrument": 'OPTION',
        "allowed_modes": [
            RunMode.BACKTEST,
            RunMode.PAPER,
            RunMode.LIVE,
        ],
    },
    'DirectionalOptionSelling': {
        "strategy": DirectionalOptionSelling,
        "instrument": 'OPTION',
        "allowed_modes": [
            RunMode.BACKTEST,
            RunMode.PAPER,
            RunMode.LIVE,
        ],
    },
    'FuturesEMAHighLow': {
        "strategy": FuturesEMAHighLow,
        "instrument": 'FUTURE',
        "allowed_modes": [
            RunMode.BACKTEST,
            RunMode.PAPER,
            RunMode.LIVE,
        ],
    },
    'Futures_EMA_Momentum': {
        "strategy": FuturesEMAMomentum,
        "instrument": 'FUTURE',
        "allowed_modes": [
            RunMode.BACKTEST,
            RunMode.PAPER,
            RunMode.LIVE,
        ],
    },
    'IPOBreakout': {
        "strategy": IPOBreakout,
        "instrument": 'EQUITY',
        "allowed_modes": [
            RunMode.BACKTEST,
            RunMode.PAPER,
            RunMode.LIVE,
        ],
    },
    'LEAPS_RSI': {
        "strategy": LeapsQuarterly,
        "instrument": 'OPTION',
        "allowed_modes": [
            RunMode.BACKTEST,
            RunMode.PAPER,
            RunMode.LIVE,
        ],
    },
    'LiquiditySweepStrategy': {
        "strategy": LiquiditySweepStrategy,
        "instrument": 'FUTURE',
        "allowed_modes": [
            RunMode.BACKTEST,
            RunMode.PAPER,
            RunMode.LIVE,
        ],
    },
    'MagicalLines': {
        "strategy": MagicalLines,
        "instrument": 'OPTION',
        "allowed_modes": [
            RunMode.BACKTEST,
            RunMode.PAPER,
            RunMode.LIVE,
        ],
    },
    'NiftyDOS': {
        "strategy": NiftyDOS,
        "instrument": 'OPTION',
        "allowed_modes": [
            RunMode.BACKTEST,
            RunMode.PAPER,
            RunMode.LIVE,
        ],
    },
    'NiftyIntradayMagicalLine': {
        "strategy": NiftyIntradayMagicalLine,
        "instrument": 'OPTION',
        "allowed_modes": [
            RunMode.BACKTEST,
            RunMode.PAPER,
            RunMode.LIVE,
        ],
    },
    'NiftySMA9Weekly': {
        "strategy": NiftySMA9Weekly,
        "instrument": 'OPTION',
        "allowed_modes": [
            RunMode.BACKTEST,
            RunMode.PAPER,
            RunMode.LIVE,
        ],
    },
    'OIPositionalBuy': {
        "strategy": OIPositionalBuy,
        "instrument": 'OPTION',
        "allowed_modes": [
            RunMode.BACKTEST,
            RunMode.PAPER,
            RunMode.LIVE,
        ],
    },
    'OneDayMagicalLine': {
        "strategy": OneDayMagicalLine,
        "instrument": 'OPTION',
        "allowed_modes": [
            RunMode.BACKTEST,
            RunMode.PAPER,
            RunMode.LIVE,
        ],
    },
    'OptionBuildup': {
        "strategy": OptionBuildup,
        "instrument": 'OPTION',
        "allowed_modes": [
            RunMode.BACKTEST,
            RunMode.PAPER,
            RunMode.LIVE,
        ],
    },
    'RSIBreadAndButter': {
        "strategy": RSIBreadAndButter,
        "instrument": 'FUTURE',
        "allowed_modes": [
            RunMode.BACKTEST,
            RunMode.PAPER,
            RunMode.LIVE,
        ],
    },
    'SignalFloodTest': {
        "strategy": SignalFloodTestStrategy,
        "instrument": 'FUTURE',
        "allowed_modes": [
            RunMode.PAPER,
            RunMode.LIVE,
        ],
    },
    'SuperTrendStockRider': {
        "strategy": SuperTrendStockRider,
        "instrument": 'EQUITY',
        "allowed_modes": [
            RunMode.BACKTEST,
            RunMode.PAPER,
            RunMode.LIVE,
        ],
    },
}
