# AUTO-GENERATED by tools/strategy_manifest — DO NOT EDIT
# Regenerate: python -m tools.strategy_manifest generate

from run.config import RunMode

STRATEGY_RUNTIME_SPEC: dict = {
    'BTCZeroDTE': {
        RunMode.BACKTEST: {
            'data': {},
        },
        RunMode.PAPER: {
            'data': {},
        },
        RunMode.LIVE: {
            'data': {},
        },
    },
    'BTCZeroDTEElevenPM': {
        RunMode.BACKTEST: {
            'data': {},
        },
        RunMode.PAPER: {
            'data': {},
        },
        RunMode.LIVE: {
            'data': {},
        },
    },
    'BankNiftyBTST': {
        RunMode.BACKTEST: {
            'data': {
                'option_chain': {
                    'exchange': 'NSE',
                    'interval': '5',
                    'segment': 'OPT',
                    'api': 'DHAN',
                    'expiry_flag': 'MONTHLY',
                },
            },
        },
        RunMode.PAPER: {
            'data': {
                'option_chain': {
                    'exchange': 'NSE',
                    'interval': '5',
                    'segment': 'OPT',
                    'api': 'DHAN',
                    'expiry_flag': 'MONTHLY',
                },
            },
        },
        RunMode.LIVE: {
            'data': {
                'option_chain': {
                    'exchange': 'NSE',
                    'interval': '1',
                    'segment': 'OPT',
                },
            },
        },
    },
    'DirectionalOptionSelling': {
        RunMode.BACKTEST: {
            'data': {},
        },
        RunMode.PAPER: {
            'data': {},
        },
        RunMode.LIVE: {
            'data': {},
        },
    },
    'FuturesEMAHighLow': {
        RunMode.BACKTEST: {
            'data': {},
        },
        RunMode.PAPER: {
            'data': {},
        },
        RunMode.LIVE: {
            'data': {},
        },
    },
    'Futures_EMA_Momentum': {
        RunMode.BACKTEST: {
            'data': {},
        },
        RunMode.PAPER: {
            'data': {},
        },
        RunMode.LIVE: {
            'data': {},
        },
    },
    'IPOBreakout': {
        RunMode.BACKTEST: {
            'data': {
                'ohlc': {
                    'exchange': 'NSE',
                    'interval': '5',
                },
            },
        },
        RunMode.PAPER: {
            'data': {
                'ohlc': {
                    'exchange': 'NSE',
                    'interval': '5',
                },
            },
        },
        RunMode.LIVE: {
            'data': {
                'ohlc': {
                    'exchange': 'NSE',
                    'interval': '5',
                },
            },
        },
    },
    'LEAPS_RSI': {
        RunMode.BACKTEST: {
            'data': {
                'option_chain': {
                    'exchange': 'NSE',
                    'interval': '60',
                    'segment': 'OPT',
                    'api': 'DHAN',
                    'expiry_flag': 'MONTHLY',
                },
            },
        },
        RunMode.PAPER: {
            'data': {
                'option_chain': {
                    'exchange': 'NSE',
                    'interval': '60',
                    'segment': 'OPT',
                    'api': 'DHAN',
                    'expiry_flag': 'MONTHLY',
                },
            },
        },
        RunMode.LIVE: {
            'data': {
                'option_chain': {
                    'exchange': 'NSE',
                    'interval': '1',
                    'segment': 'OPT',
                },
            },
        },
    },
    'LiquiditySweepStrategy': {
        RunMode.BACKTEST: {
            'data': {},
        },
        RunMode.PAPER: {
            'data': {},
        },
        RunMode.LIVE: {
            'data': {},
        },
    },
    'MagicalLines': {
        RunMode.BACKTEST: {
            'data': {
                'option_chain': {
                    'exchange': 'NSE',
                    'interval': '30',
                    'segment': 'OPT',
                    'api': 'DHAN',
                    'expiry_flag': 'MONTHLY',
                },
            },
        },
        RunMode.PAPER: {
            'data': {
                'option_chain': {
                    'exchange': 'NSE',
                    'interval': '30',
                    'segment': 'OPT',
                    'api': 'DHAN',
                    'expiry_flag': 'MONTHLY',
                },
            },
        },
        RunMode.LIVE: {
            'data': {
                'option_chain': {
                    'exchange': 'NSE',
                    'interval': '1',
                    'segment': 'OPT',
                },
            },
        },
    },
    'NiftyDOS': {
        RunMode.BACKTEST: {
            'data': {
                'option_chain': {
                    'exchange': 'NSE',
                    'interval': '30',
                    'segment': 'OPT',
                    'api': 'KOTAK',
                    'expiry_flag': 'WEEK',
                },
            },
        },
        RunMode.PAPER: {
            'data': {
                'option_chain': {
                    'exchange': 'NSE',
                    'interval': '30',
                    'segment': 'OPT',
                    'api': 'KOTAK',
                    'expiry_flag': 'WEEK',
                },
            },
        },
        RunMode.LIVE: {
            'data': {
                'option_chain': {
                    'exchange': 'NSE',
                    'interval': '1',
                    'segment': 'OPT',
                    'api': 'KOTAK',
                    'expiry_flag': 'WEEK',
                },
            },
        },
    },
    'NiftyIntradayMagicalLine': {
        RunMode.BACKTEST: {
            'data': {
                'option_chain': {
                    'exchange': 'NSE',
                    'interval': '15',
                    'segment': 'OPT',
                    'api': 'DHAN',
                    'expiry_flag': 'MONTHLY',
                },
            },
        },
        RunMode.PAPER: {
            'data': {
                'option_chain': {
                    'exchange': 'NSE',
                    'interval': '15',
                    'segment': 'OPT',
                    'api': 'DHAN',
                    'expiry_flag': 'MONTHLY',
                },
            },
        },
        RunMode.LIVE: {
            'data': {
                'option_chain': {
                    'exchange': 'NSE',
                    'interval': '1',
                    'segment': 'OPT',
                },
            },
        },
    },
    'NiftySMA9Weekly': {
        RunMode.BACKTEST: {
            'data': {
                'option_chain': {
                    'exchange': 'NSE',
                    'interval': '120',
                    'segment': 'OPT',
                    'api': 'KOTAK',
                    'expiry_flag': 'WEEK',
                },
            },
        },
        RunMode.PAPER: {
            'data': {
                'option_chain': {
                    'exchange': 'NSE',
                    'interval': '120',
                    'segment': 'OPT',
                    'api': 'KOTAK',
                    'expiry_flag': 'WEEK',
                },
            },
        },
        RunMode.LIVE: {
            'data': {
                'option_chain': {
                    'exchange': 'NSE',
                    'interval': '1',
                    'segment': 'OPT',
                    'api': 'KOTAK',
                    'expiry_flag': 'WEEK',
                },
            },
        },
    },
    'OIPositionalBuy': {
        RunMode.BACKTEST: {
            'data': {
                'option_chain': {
                    'exchange': 'NSE',
                    'interval': '15',
                    'segment': 'OPT',
                    'api': 'DHAN',
                    'expiry_flag': 'MONTHLY',
                },
            },
        },
        RunMode.PAPER: {
            'data': {
                'option_chain': {
                    'exchange': 'NSE',
                    'interval': '15',
                    'segment': 'OPT',
                    'api': 'DHAN',
                    'expiry_flag': 'MONTHLY',
                },
            },
        },
        RunMode.LIVE: {
            'data': {
                'option_chain': {
                    'exchange': 'NSE',
                    'interval': '15',
                    'segment': 'OPT',
                    'api': 'DHAN',
                    'expiry_flag': 'MONTHLY',
                },
            },
        },
    },
    'OneDayMagicalLine': {
        RunMode.BACKTEST: {
            'data': {},
        },
        RunMode.PAPER: {
            'data': {},
        },
        RunMode.LIVE: {
            'data': {},
        },
    },
    'OptionBuildup': {
        RunMode.BACKTEST: {
            'data': {
                'option_chain': {
                    'exchange': 'NSE',
                    'interval': '15',
                    'segment': 'OPT',
                    'api': 'DHAN',
                    'expiry_flag': 'MONTHLY',
                },
            },
        },
        RunMode.PAPER: {
            'data': {
                'option_chain': {
                    'exchange': 'NSE',
                    'interval': '15',
                    'segment': 'OPT',
                    'api': 'DHAN',
                    'expiry_flag': 'MONTHLY',
                },
            },
        },
        RunMode.LIVE: {
            'data': {
                'option_chain': {
                    'exchange': 'NSE',
                    'interval': '15',
                    'segment': 'OPT',
                    'api': 'DHAN',
                    'expiry_flag': 'MONTHLY',
                },
            },
        },
    },
    'RSIBreadAndButter': {
        RunMode.BACKTEST: {
            'data': {},
        },
        RunMode.PAPER: {
            'data': {},
        },
        RunMode.LIVE: {
            'data': {},
        },
    },
    'SignalFloodTest': {
        RunMode.PAPER: {
            'data': {},
        },
        RunMode.LIVE: {
            'data': {},
        },
    },
    'SuperTrendStockRider': {
        RunMode.BACKTEST: {
            'data': {
                'exchange': 'NSE',
                'interval': 'DAY',
                'sector': 'EQ',
            },
        },
        RunMode.PAPER: {
            'data': {
                'exchange': 'NSE',
                'interval': 'DAY',
                'sector': 'EQ',
            },
        },
        RunMode.LIVE: {
            'data': {
                'exchange': 'NSE',
                'interval': 'DAY',
                'sector': 'EQ',
            },
        },
    },
}
