# AUTO-GENERATED by tools/strategy_manifest — DO NOT EDIT
# Regenerate: python -m tools.strategy_manifest generate

GENERATED_STRATEGY_SUBSCRIPTIONS: dict = {
    'BTCZeroDTE': {
        'BarClosed': {
            'enabled': False,
        },
        'FeedDisconnected': {
            'enabled': True,
        },
        'FeedRecovered': {
            'enabled': True,
        },
        'IntentCreated': {
            'enabled': True,
        },
        'IntentFilled': {
            'enabled': True,
        },
        'PositionClosed': {
            'enabled': True,
        },
        'QuoteUpdated': {
            'enabled': False,
            'symbols': [
                'BTCUSD',
                'ETHUSD',
            ],
        },
        'ScheduledSlot': {
            'enabled': True,
            'symbols': [
                'BTCUSD',
                'ETHUSD',
            ],
        },
    },
    'BTCZeroDTEElevenPM': {
        'BarClosed': {
            'enabled': False,
        },
        'FeedDisconnected': {
            'enabled': True,
        },
        'FeedRecovered': {
            'enabled': True,
        },
        'IntentCreated': {
            'enabled': True,
        },
        'IntentFilled': {
            'enabled': True,
        },
        'PositionClosed': {
            'enabled': True,
        },
        'QuoteUpdated': {
            'enabled': False,
            'symbols': [
                'BTCUSD',
            ],
        },
        'ScheduledSlot': {
            'enabled': True,
            'symbols': [
                'BTCUSD',
            ],
        },
    },
    'BankNiftyBTST': {
        'BarClosed': {
            'enabled': False,
        },
        'FeedDisconnected': {
            'enabled': True,
        },
        'FeedRecovered': {
            'enabled': True,
        },
        'IntentCreated': {
            'enabled': True,
        },
        'IntentFilled': {
            'enabled': True,
        },
        'PositionClosed': {
            'enabled': True,
        },
        'QuoteUpdated': {
            'enabled': True,
            'symbols': [
                'BANKNIFTY',
            ],
        },
        'ScheduledSlot': {
            'enabled': True,
            'symbols': [
                'BANKNIFTY',
            ],
        },
    },
    'DirectionalOptionSelling': {
        'BarClosed': {
            'enabled': True,
            'timeframes': [
                '60',
                '4h',
                '1d',
            ],
            'symbols': [
                'BTCUSD',
                'ETHUSD',
            ],
        },
        'FeedDisconnected': {
            'enabled': True,
        },
        'FeedRecovered': {
            'enabled': True,
        },
        'IntentCreated': {
            'enabled': True,
        },
        'IntentFilled': {
            'enabled': True,
        },
        'PositionClosed': {
            'enabled': True,
        },
        'QuoteUpdated': {
            'enabled': True,
            'symbols': [
                'BTCUSD',
                'ETHUSD',
            ],
        },
        'ScheduledSlot': {
            'enabled': False,
            'symbols': [
                'BTCUSD',
                'ETHUSD',
            ],
        },
    },
    'FuturesEMAHighLow': {
        'BarClosed': {
            'enabled': True,
            'timeframes': [
                '60',
            ],
            'symbols': [
                'NIFTY',
            ],
        },
        'FeedDisconnected': {
            'enabled': True,
        },
        'FeedRecovered': {
            'enabled': True,
        },
        'IntentCreated': {
            'enabled': True,
        },
        'IntentFilled': {
            'enabled': True,
        },
        'PositionClosed': {
            'enabled': True,
        },
        'QuoteUpdated': {
            'enabled': False,
            'symbols': [
                'NIFTY',
            ],
        },
        'ScheduledSlot': {
            'enabled': False,
            'symbols': [
                'NIFTY',
            ],
        },
    },
    'Futures_EMA_Momentum': {
        'BarClosed': {
            'enabled': True,
            'timeframes': [
                '60',
            ],
            'symbols': [
                'BTCUSD',
            ],
        },
        'FeedDisconnected': {
            'enabled': True,
        },
        'FeedRecovered': {
            'enabled': True,
        },
        'IntentCreated': {
            'enabled': True,
        },
        'IntentFilled': {
            'enabled': True,
        },
        'PositionClosed': {
            'enabled': True,
        },
        'QuoteUpdated': {
            'enabled': False,
            'symbols': [
                'BTCUSD',
            ],
        },
        'ScheduledSlot': {
            'enabled': False,
            'symbols': [
                'BTCUSD',
            ],
        },
    },
    'IPOBreakout': {
        'BarClosed': {
            'enabled': True,
            'timeframes': [
                'DAY',
            ],
        },
        'FeedDisconnected': {
            'enabled': True,
        },
        'FeedRecovered': {
            'enabled': True,
        },
        'IntentCreated': {
            'enabled': True,
        },
        'IntentFilled': {
            'enabled': True,
        },
        'PositionClosed': {
            'enabled': True,
        },
        'QuoteUpdated': {
            'enabled': False,
        },
        'ScheduledSlot': {
            'enabled': False,
        },
    },
    'LEAPS_RSI': {
        'BarClosed': {
            'enabled': True,
            'timeframes': [
                '60',
            ],
            'symbols': [
                'NIFTY',
            ],
        },
        'FeedDisconnected': {
            'enabled': True,
        },
        'FeedRecovered': {
            'enabled': True,
        },
        'IntentCreated': {
            'enabled': True,
        },
        'IntentFilled': {
            'enabled': True,
        },
        'PositionClosed': {
            'enabled': True,
        },
        'QuoteUpdated': {
            'enabled': False,
            'symbols': [
                'NIFTY',
            ],
        },
        'ScheduledSlot': {
            'enabled': False,
            'symbols': [
                'NIFTY',
            ],
        },
    },
    'LiquiditySweepStrategy': {
        'BarClosed': {
            'enabled': True,
            'timeframes': [
                '1',
                '5',
                '4h',
            ],
            'symbols': [
                'BTCUSD',
            ],
        },
        'FeedDisconnected': {
            'enabled': True,
        },
        'FeedRecovered': {
            'enabled': True,
        },
        'IntentCreated': {
            'enabled': True,
        },
        'IntentFilled': {
            'enabled': True,
        },
        'PositionClosed': {
            'enabled': True,
        },
        'QuoteUpdated': {
            'enabled': False,
            'symbols': [
                'BTCUSD',
            ],
        },
        'ScheduledSlot': {
            'enabled': False,
            'symbols': [
                'BTCUSD',
            ],
        },
    },
    'MagicalLines': {
        'BarClosed': {
            'enabled': True,
            'timeframes': [
                'DAY',
            ],
            'symbols': [
                'NIFTY',
            ],
        },
        'FeedDisconnected': {
            'enabled': True,
        },
        'FeedRecovered': {
            'enabled': True,
        },
        'IntentCreated': {
            'enabled': True,
        },
        'IntentFilled': {
            'enabled': True,
        },
        'PositionClosed': {
            'enabled': True,
        },
        'QuoteUpdated': {
            'enabled': False,
            'symbols': [
                'NIFTY',
            ],
        },
        'ScheduledSlot': {
            'enabled': False,
            'symbols': [
                'NIFTY',
            ],
        },
    },
    'NiftyIntradayMagicalLine': {
        'BarClosed': {
            'enabled': True,
            'timeframes': [
                '15',
            ],
            'symbols': [
                'NIFTY',
            ],
        },
        'FeedDisconnected': {
            'enabled': True,
        },
        'FeedRecovered': {
            'enabled': True,
        },
        'IntentCreated': {
            'enabled': True,
        },
        'IntentFilled': {
            'enabled': True,
        },
        'PositionClosed': {
            'enabled': True,
        },
        'QuoteUpdated': {
            'enabled': False,
            'symbols': [
                'NIFTY',
            ],
        },
        'ScheduledSlot': {
            'enabled': False,
            'symbols': [
                'NIFTY',
            ],
        },
    },
    'NiftySMA9Weekly': {
        'BarClosed': {
            'enabled': True,
            'timeframes': [
                '120',
            ],
            'symbols': [
                'NIFTY',
            ],
        },
        'FeedDisconnected': {
            'enabled': True,
        },
        'FeedRecovered': {
            'enabled': True,
        },
        'IntentCreated': {
            'enabled': True,
        },
        'IntentFilled': {
            'enabled': True,
        },
        'PositionClosed': {
            'enabled': True,
        },
        'QuoteUpdated': {
            'enabled': False,
            'symbols': [
                'NIFTY',
            ],
        },
        'ScheduledSlot': {
            'enabled': False,
            'symbols': [
                'NIFTY',
            ],
        },
    },
    'OIPositionalBuy': {
        'BarClosed': {
            'enabled': True,
            'timeframes': [
                '15',
            ],
            'symbols': [
                'NIFTY',
            ],
        },
        'FeedDisconnected': {
            'enabled': True,
        },
        'FeedRecovered': {
            'enabled': True,
        },
        'IntentCreated': {
            'enabled': True,
        },
        'IntentFilled': {
            'enabled': True,
        },
        'PositionClosed': {
            'enabled': True,
        },
        'QuoteUpdated': {
            'enabled': False,
            'symbols': [
                'NIFTY',
            ],
        },
        'ScheduledSlot': {
            'enabled': False,
            'symbols': [
                'NIFTY',
            ],
        },
    },
    'OneDayMagicalLine': {
        'BarClosed': {
            'enabled': True,
            'timeframes': [
                '60',
            ],
            'symbols': [
                'BTCUSD',
            ],
        },
        'FeedDisconnected': {
            'enabled': True,
        },
        'FeedRecovered': {
            'enabled': True,
        },
        'IntentCreated': {
            'enabled': True,
        },
        'IntentFilled': {
            'enabled': True,
        },
        'PositionClosed': {
            'enabled': True,
        },
        'QuoteUpdated': {
            'enabled': False,
            'symbols': [
                'BTCUSD',
            ],
        },
        'ScheduledSlot': {
            'enabled': False,
            'symbols': [
                'BTCUSD',
            ],
        },
    },
    'OptionBuildup': {
        'BarClosed': {
            'enabled': True,
            'timeframes': [
                '15',
            ],
            'symbols': [
                'NIFTY',
            ],
        },
        'FeedDisconnected': {
            'enabled': True,
        },
        'FeedRecovered': {
            'enabled': True,
        },
        'IntentCreated': {
            'enabled': True,
        },
        'IntentFilled': {
            'enabled': True,
        },
        'PositionClosed': {
            'enabled': True,
        },
        'QuoteUpdated': {
            'enabled': False,
            'symbols': [
                'NIFTY',
            ],
        },
        'ScheduledSlot': {
            'enabled': False,
            'symbols': [
                'NIFTY',
            ],
        },
    },
    'RSIBreadAndButter': {
        'BarClosed': {
            'enabled': True,
            'timeframes': [
                '1',
            ],
            'symbols': [
                'BTCUSD',
            ],
        },
        'FeedDisconnected': {
            'enabled': True,
        },
        'FeedRecovered': {
            'enabled': True,
        },
        'IntentCreated': {
            'enabled': True,
        },
        'IntentFilled': {
            'enabled': True,
        },
        'PositionClosed': {
            'enabled': True,
        },
        'QuoteUpdated': {
            'enabled': False,
            'symbols': [
                'BTCUSD',
            ],
        },
        'ScheduledSlot': {
            'enabled': False,
            'symbols': [
                'BTCUSD',
            ],
        },
    },
    'SignalFloodTest': {
        'BarClosed': {
            'enabled': True,
            'timeframes': [
                '1',
            ],
        },
        'FeedDisconnected': {
            'enabled': True,
        },
        'FeedRecovered': {
            'enabled': True,
        },
        'IntentCreated': {
            'enabled': True,
        },
        'IntentFilled': {
            'enabled': True,
        },
        'PositionClosed': {
            'enabled': True,
        },
        'QuoteUpdated': {
            'enabled': False,
        },
        'ScheduledSlot': {
            'enabled': False,
        },
    },
}
