"""Emit generated Python modules from strategy manifests."""

from __future__ import annotations

import json
import textwrap
from pathlib import Path
from typing import Any, Dict, List

from tools.strategy_manifest.schema import StrategyManifest

GENERATED_DIR = Path(__file__).resolve().parents[2] / "core" / "strategies" / "_generated"
HEADER = '''# AUTO-GENERATED by tools/strategy_manifest — DO NOT EDIT
# Regenerate: python -m tools.strategy_manifest generate
'''


def _py_repr(value: Any, indent: int = 0) -> str:
    pad = " " * indent
    if value is None:
        return "None"
    if isinstance(value, bool):
        return "True" if value else "False"
    if isinstance(value, (int, float)):
        return repr(value)
    if isinstance(value, str):
        return repr(value)
    if isinstance(value, list):
        if not value:
            return "[]"
        inner = ",\n".join(f"{pad}    {_py_repr(v, indent + 4)}" for v in value)
        return f"[\n{inner},\n{pad}]"
    if isinstance(value, dict):
        if not value:
            return "{}"
        lines = []
        for k, v in value.items():
            lines.append(f"{pad}    {repr(k)}: {_py_repr(v, indent + 4)},")
        return "{\n" + "\n".join(lines) + f"\n{pad}}}"
    return repr(value)


def _run_mode_ref(mode: str) -> str:
    return f"RunMode.{mode.upper()}"


def _resolve_data_block(manifest: StrategyManifest, mode: str) -> Dict[str, Any]:
    data = manifest.data or {}
    key = mode.lower()
    if key in data:
        block = data[key]
        return dict(block) if isinstance(block, dict) else {}
    if "default" in data:
        block = data["default"]
        return dict(block) if isinstance(block, dict) else {}
    return {}


def emit_registry(manifests: List[StrategyManifest]) -> str:
    imports: Dict[str, str] = {}
    entries: List[str] = []

    for m in sorted(manifests, key=lambda x: x.id):
        mod = m.implementation.module
        cls_name = m.implementation.class_name
        imports[mod] = cls_name
        modes = ",\n            ".join(_run_mode_ref(mode) for mode in m.allowed_modes)
        entries.append(
            f"    {m.id!r}: {{\n"
            f'        "strategy": {cls_name},\n'
            f'        "instrument": {m.instrument!r},\n'
            f'        "allowed_modes": [\n'
            f"            {modes},\n"
            f"        ],\n"
            f"    }},"
        )

    import_lines = []
    for mod in sorted(imports):
        cls_name = imports[mod]
        import_lines.append(f"from {mod} import {cls_name}")

    body = "\n".join(entries)
    imports_block = "\n".join(import_lines)
    return (
        f"{HEADER}\n"
        f"from run.config import RunMode\n\n"
        f"{imports_block}\n\n"
        f"GENERATED_STRATEGY_MAP = {{\n    {body}\n}}\n"
    )


def _build_profile_dict(manifest: StrategyManifest) -> Dict[str, Any]:
    profile: Dict[str, Any] = {}
    if manifest.symbols is not None or "symbols" in manifest.profile:
        profile["symbols"] = manifest.symbols
    if manifest.exchange:
        profile["exchange"] = manifest.exchange
    if manifest.schedule.eval_mode and manifest.schedule.eval_mode != "live_feed":
        profile["eval_mode"] = manifest.schedule.eval_mode
    if manifest.broker.delta:
        profile["delta"] = manifest.broker.delta
    for key in ("live", "backtest"):
        if key in manifest.profile:
            profile[key] = manifest.profile[key]
    return profile


def emit_profiles(manifests: List[StrategyManifest]) -> str:
    entries = []
    for m in sorted(manifests, key=lambda x: x.id):
        prof = _build_profile_dict(m)
        entries.append(f"    {m.id!r}: {_py_repr(prof, 4)},")
    body = "\n".join(entries)
    return f"{HEADER}\nSTRATEGY_PROFILES: dict = {{\n{body}\n}}\n"


def emit_runtime_spec(manifests: List[StrategyManifest]) -> str:
    entries: List[str] = []
    for m in sorted(manifests, key=lambda x: x.id):
        mode_blocks: List[str] = []
        for mode in m.allowed_modes:
            data_block = _resolve_data_block(m, mode)
            inner = _py_repr({"data": data_block.get("data", data_block)}, 8)
            mode_blocks.append(f"        {_run_mode_ref(mode)}: {inner},")
        block = "\n".join(mode_blocks)
        entries.append(f"    {m.id!r}: {{\n{block}\n    }},")
    body = "\n".join(entries)
    return (
        f"{HEADER}\n"
        f"from run.config import RunMode\n\n"
        f"STRATEGY_RUNTIME_SPEC: dict = {{\n{body}\n}}\n"
    )


def emit_meta_keys(manifests: List[StrategyManifest]) -> str:
    legacy: Dict[str, str] = {}
    aliases: Dict[str, str] = {}
    for m in manifests:
        if m.dependencies.meta_key:
            legacy[m.id] = m.dependencies.meta_key
        for alias, target in (m.dependencies.meta_aliases or {}).items():
            aliases[str(alias)] = str(target)
    return (
        f"{HEADER}\n"
        f"GENERATED_LEGACY_META_KEYS: dict = {_py_repr(legacy, 0)}\n\n"
        f"GENERATED_META_ALIASES: dict = {_py_repr(aliases, 0)}\n"
    )


def emit_aliases(manifests: List[StrategyManifest]) -> str:
    mapping: Dict[str, str] = {}
    for m in manifests:
        for alias in m.aliases:
            mapping[alias] = m.id
    return f"{HEADER}\nGENERATED_STRATEGY_ALIASES: dict = {_py_repr(mapping, 0)}\n"


def emit_subscriptions(manifests: List[StrategyManifest]) -> str:
    entries = []
    for m in sorted(manifests, key=lambda x: x.id):
        entries.append(f"    {m.id!r}: {_py_repr(m.subscriptions.to_dict(), 4)},")
    body = "\n".join(entries)
    return f"{HEADER}\nGENERATED_STRATEGY_SUBSCRIPTIONS: dict = {{\n{body}\n}}\n"


def emit_strategy_index(manifests: List[StrategyManifest]) -> str:
    lines = [
        "# Strategy index",
        "",
        "_AUTO-GENERATED table — run `python -m tools.strategy_manifest generate` to refresh._",
        "",
        "| Registry key | Class | Instrument | Venue | Manifest |",
        "|--------------|-------|------------|-------|----------|",
    ]
    for m in sorted(manifests, key=lambda x: x.id):
        rel = ""
        if m.source_path:
            try:
                rel = m.source_path.relative_to(
                    Path(__file__).resolve().parents[2]
                ).as_posix()
            except ValueError:
                rel = str(m.source_path)
        lines.append(
            f"| `{m.id}` | `{m.implementation.class_name}` | "
            f"{m.instrument} | {m.broker.venue} | `{rel}` |"
        )
    lines.extend(
        [
            "",
            "See `docs/STRATEGY_MANIFEST.md` for the manifest workflow.",
            "",
        ]
    )
    return "\n".join(lines)


def emit_readme(manifest: StrategyManifest) -> str:
    doc = manifest.documentation
    title = doc.title or manifest.id
    overview = doc.overview or "_(add overview in strategy.yaml → documentation.overview)_"
    rules = doc.rules or "_(add rules in strategy.yaml → documentation.rules)_"
    run_cmd = doc.run_command or f"python -m run.main --engine-id <engine_id>"
    eval_mode = manifest.schedule.eval_mode
    tf = manifest.timeframe if manifest.timeframe is not None else "None (scheduled)"
    symbols = ", ".join(manifest.symbols or []) or "universe-driven"

    return textwrap.dedent(
        f"""\
        # {title}

        > Auto-generated from `strategy.yaml`. Edit manifest and run:
        > `python -m tools.strategy_manifest generate --readme {manifest.id}`

        Registry: `STRATEGY_MAP["{manifest.id}"]`  
        Implementation: `{manifest.implementation.module}.{manifest.implementation.class_name}`  
        Manifest: `{manifest.source_path}`

        ## Overview

        {overview.strip()}

        ## Evaluation

        | Item | Value |
        |------|-------|
        | Eval mode | `{eval_mode}` |
        | Timeframe | `{tf}` |
        | Symbols | {symbols} |
        | Venue | `{manifest.broker.venue}` |
        | Exits | `should_exit` every closed bar (before entries) |

        ## Rules

        {rules.strip()}

        ## Run

        ```bash
        {run_cmd.strip()}
        ```

        ## Wiring

        | Item | Location |
        |------|----------|
        | Manifest | `{manifest.source_path}` |
        | Generated registry | `core/strategies/_generated/` |
        """
    )


def write_generated_files(
    manifests: List[StrategyManifest],
    *,
    out_dir: Path | None = None,
    readme_ids: List[str] | None = None,
) -> List[Path]:
    out = out_dir or GENERATED_DIR
    out.mkdir(parents=True, exist_ok=True)

    written: List[Path] = []
    files = {
        "registry_entries.py": emit_registry(manifests),
        "profiles.py": emit_profiles(manifests),
        "runtime_spec.py": emit_runtime_spec(manifests),
        "meta_keys.py": emit_meta_keys(manifests),
        "aliases.py": emit_aliases(manifests),
        "subscriptions.py": emit_subscriptions(manifests),
    }
    for name, content in files.items():
        path = out / name
        path.write_text(content, encoding="utf-8")
        written.append(path)

    init_py = out / "__init__.py"
    if not init_py.exists():
        init_py.write_text(
            '"""Generated strategy wiring (registry, profiles, runtime spec)."""\n',
            encoding="utf-8",
        )
        written.append(init_py)

    index_path = Path(__file__).resolve().parents[2] / "docs" / "STRATEGY_INDEX.generated.md"
    index_path.write_text(emit_strategy_index(manifests), encoding="utf-8")
    written.append(index_path)

    if readme_ids:
        by_id = {m.id: m for m in manifests}
        for sid in readme_ids:
            m = by_id.get(sid)
            if not m or not m.source_path:
                continue
            readme_path = m.source_path.parent / "readme.md"
            readme_path.write_text(emit_readme(m), encoding="utf-8")
            written.append(readme_path)

    return written
